import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faHome,
  faBars,
  faXmark,
  faEllipsis,
  faEye,
  faEyeSlash,
  faEdit,
  faCamera,
  faCheck,
  faCircleCheck,
  faCircleExclamation,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faCloudArrowUp,
  faPlus,
  faMinus,
  faLocationDot,
  faAngleUp,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faGear,
  faRightToBracket,
  faRightFromBracket,
  faRightLong,
  faFlag,
  faStar,
  faTrash,
  faUser,
  faUserPlus,
  faCircleUser,
  faCircleQuestion,
  faPeopleGroup,
  faCircleInfo
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { faStar as farFaStar } from '@fortawesome/free-regular-svg-icons'

library.add(
  faHome,
  faBars,
  faXmark,
  faEllipsis,
  faEye,
  faEyeSlash,
  faEdit,
  faCamera,
  faCheck,
  faCircleCheck,
  faCircleExclamation,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faCloudArrowUp,
  faPlus,
  faMinus,
  faLocationDot,
  faAngleUp,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faGear,
  faRightLong,
  faRightToBracket,
  faRightFromBracket,
  faFlag,
  faStar,
  faTrash,
  faUser,
  faUserPlus,
  faCircleUser,
  faPeopleGroup,
  faCircleInfo,
  faCircleQuestion,
  farFaStar
)

export default FontAwesomeIcon
